### ISSUE TITLE
Accessing Concordion Table data in a Map

### ISSUE THREAD

**Issue by DragosCotoc** [concordion/concordion#313]
Hi Concordion Team,

This might be related with the already raised issue [Concordion Table Support](https://github.com/concordion/concordion/issues/169). Apologies in advanced if it's the case.

Currently working on a way to access the table data in a map like format, map key being the column value and the value associated to the key being the column value.

Found two approaches so far, one using an ONGL map and the other using the #TEXT variable.
- the approach with the OGNL map has it's disadvantage that it requires to create the OGNL map - example 1 and 2 from SpecificationWithOGNLMap.md
- the approach with the #TEXT variable has it's disadvantage that if we change the order of the columns in the input table the method to generate the input message will not work as expected since we are using a string array - example 2 from SpecificationWithTEXTVariable.html

Can you please help with your input if there is a way in Concordion to access the table data in a map like form?
If not, is this something that you consider in the future to have and implementation that will expose a variable like #TABLEDATA to store the table data in the map like format?

Created a small project to highlight the above: https://github.com/DragosCotoc/FunctionalSpecifications/tree/main

Markdown files SpecificationWithOGNLMap.md and SpecificationWithTEXTVariable.md:
https://github.com/DragosCotoc/FunctionalSpecifications/tree/main/src/test/resources/fixtures

HTML reports SpecificationWithOGNLMap.html and SpecificationWithTEXTVariable.html:
https://github.com/DragosCotoc/FunctionalSpecifications/tree/main/src/test/resources/results

Thank you and regards, 
Dragos

**Comment by nigelcharman** [comment]
Hi Dragos

There is currently no way to achieve this with Concordion. It would seem 
to be useful and something we should add to Concordion.

I'm thinking we should be able to use the set command to set a variable 
a Map of the table data, and the execute command to pass a Map of the 
table data as a parameter.

I won't have any time to do this for at least the next 4 weeks. Let me 
know if you're keen to give it a go yourself?

thanks
Nigel

**Comment by DragosCotoc** [comment]
Hi @nigelcharman,

Thank you for your input!
I can give it a try in the following weeks and update here with my findings/progress.

Thank you and regards,
Dragos

**Comment by nigelcharman** [comment]
Hi Dragos

Here's some info to help you understand the codebase a bit more.

The canonical format is HTML so you should build the HTML implementation first. Have a look at the commands[https://github.com/concordion/concordion/tree/master/src/main/java/org/concordion/internal/command], especially the execute on a table command[https://github.com/concordion/concordion/blob/master/src/main/java/org/concordion/internal/command/executeCommand/modificationStrategies/ExecuteCommandTableModification.java]. If you decide to use a text decorator, such as #TABLETEXT rather than a command, see local text decorator[https://github.com/concordion/concordion/blob/master/src/main/java/org/concordion/internal/command/LocalTextDecorator.java]. I'd suggest playing with both a command and a text decorator to determine which one works best for you. One downside of using a command is that we only allow a single command on an HTML element by default.

If you implement a text decorator, it should just work with Markdown. If you implement a command, it may need some additional effort to translate it to the HTML syntax. It may work OK by adding a c: prefix to the command on the link title. But if you want a custom Markdown syntax, you will need to extend the Markdown parser[https://github.com/concordion/concordion/tree/master/src/main/java/org/concordion/internal/parser/flexmark] to parse the syntax and translate it to HTML.

I hope that helps. Let me know if you have any questions.

Cheers
Nigel

**Comment by nigelcharman** [comment]
One other thing that is useful if you need to debug the Markdown parser is to output a copy of the HTML document[https://concordion.github.io/concordion/latest/spec/annotation/ConcordionOptions.html].

18/03/2021 13:20:51 Nigel Charman ***@***.***>:

> Hi Dragos
> 
> Here's some info to help you understand the codebase a bit more.
> 
> The canonical format is HTML so you should build the HTML implementation first. Have a look at the commands[https://github.com/concordion/concordion/tree/master/src/main/java/org/concordion/internal/command], especially the execute on a table command[https://github.com/concordion/concordion/blob/master/src/main/java/org/concordion/internal/command/executeCommand/modificationStrategies/ExecuteCommandTableModification.java]. If you decide to use a text decorator, such as #TABLETEXT rather than a command, see local text decorator[https://github.com/concordion/concordion/blob/master/src/main/java/org/concordion/internal/command/LocalTextDecorator.java]. I'd suggest playing with both a command and a text decorator to determine which one works best for you. One downside of using a command is that we only allow a single command on an HTML element by default.
> 
> If you implement a text decorator, it should just work with Markdown. If you implement a command, it may need some additional effort to translate it to the HTML syntax. It may work OK by adding a c: prefix to the command on the link title. But if you want a custom Markdown syntax, you will need to extend the Markdown parser[https://github.com/concordion/concordion/tree/master/src/main/java/org/concordion/internal/parser/flexmark] to parse the syntax and translate it to HTML.
> 
> I hope that helps. Let me know if you have any questions.
> 
> Cheers
> Nigel
