### ISSUE TITLE
test containing  tests in success and tests ignored should have success result

### ISSUE THREAD

**Issue by dev0101** [concordion/concordion#86]
When you define a parent test who runs several child tests (with some tests who are ignored and others successed), the result of the parent test is ignored.
The result of the parent test should be success like JUnit. Isn't it?

**Comment by nigelcharman** [comment]
The current behaviour is that a specification can only return a single result to an index spec. If the specification contains any errors or failures, a failure result is returned. Else if the spec contains any ignored test, an ignored result is returned. Otherwise success is returned.

This behaviour is due to change in 1.5.0 with the implementation of #72. This will aggregate all test counts to the parent spec. This new behaviour should be more in line with your expectations.

**Comment by nigelcharman** [comment]
@dev0101 Please confirm whether this is fixed in 1.5.0. thanks

**Comment by nigelcharman** [comment]
Closing, since fixed in 1.5.0.
